version: "3"

services:
  hmt-app1:
    build: .
    image: hmt-app:2.0
    container_name: hmt-app1
    volumes:
     - data:/data
    ports:
      - "5001:5000"
    networks:
      - all-hmt
#      - app-hmt

  hmt-app2:
    build: .
    image: hmt-app:2.0
    container_name: hmt-app2
    volumes:
     - data:/data
    ports:
      - "5002:5000"
    networks:
      - all-hmt
#     - app-hmt

  hmt-app3:
    build: .
    image: hmt-app:2.0
    container_name: hmt-app3
    volumes:
     - data:/data
    ports:
      - "5003:5000"
    networks:
      - all-hmt
#      - app-hmt

  redis:
    image: redis
    container_name: redis
    volumes:
      - data:/data
    ports:
      - "6379:6379"
    networks:
      - all-hmt

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - data:/data
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - all-hmt

volumes:
  data:

networks:
  all-hmt:
#  app-hmt:
